import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.lessons': 'Lessons',
    'nav.realtime.tasks': 'Real Time Tasks',
    'nav.scoreboard': 'Scoreboard',
    'nav.logout': 'Logout',
    'nav.user': 'Alex Student',
    'nav.logout.success': 'Logged out successfully',
    'nav.logout.message': 'See you next time!',
    
    // Dashboard
    'dashboard.welcome': 'Welcome to Your Environmental Journey! 🌍',
    'dashboard.subtitle': 'Explore interactive lessons about environmental protection and sustainability. Each lesson includes videos, quizzes, and hands-on activities to help you become an eco-hero!',
    'dashboard.progress': 'Progress',
    'dashboard.overall.progress': 'Overall Progress',
    'dashboard.completed': 'Completed',
    'dashboard.lessons.completed': 'Lessons completed',
    'dashboard.total.time': 'Total Time',
    'dashboard.hours.learning': 'Hours of learning',
    'dashboard.environmental.lessons': 'Environmental Lessons',
    'dashboard.active.tasks': 'Active Tasks',
    'dashboard.tasks.available': 'Tasks Available',
    'dashboard.community.size': 'Community Size',
    'dashboard.active.participants': 'Active Participants',
    'dashboard.impact.made': 'Impact Made',
    'dashboard.tasks.completed': 'Tasks Completed',
    'dashboard.keep.going': '🎯 Keep Going, Eco-Warrior!',
    'dashboard.motivation': "You're making great progress! Every lesson brings you closer to becoming an environmental champion.",
    'dashboard.view.achievements': 'View Your Achievements',
    
    // Lesson status
    'lesson.completed': '✓ Completed',
    'lesson.complete': 'Complete',
    'lesson.not.started': 'Not Started',
    'lesson.start': 'Start',
    'lesson.continue': 'Continue',
    'lesson.review': 'Review',
    
    // Difficulty levels
    'difficulty.beginner': 'Beginner',
    'difficulty.intermediate': 'Intermediate',
    'difficulty.advanced': 'Advanced',
    
    // Lessons
    'lesson.waste.management': 'Waste Management',
    'lesson.waste.management.desc': 'Learn about proper waste disposal, recycling, and composting to reduce environmental impact.',
    'lesson.water.treatment': 'Water Treatment',
    'lesson.water.treatment.desc': 'Discover how water is cleaned and purified for safe consumption and environmental protection.',
    'lesson.pollution.free': 'Pollution-Free Zones',
    'lesson.pollution.free.desc': 'Explore strategies to create and maintain clean, pollution-free environments in cities.',
    'lesson.afforestation': 'Afforestation',
    'lesson.afforestation.desc': 'Understand the importance of planting trees and creating new forests for our planet.',
    'lesson.deforestation': 'Deforestation',
    'lesson.deforestation.desc': 'Learn about the causes and effects of deforestation and how to prevent it.',
    'lesson.renewable.energy': 'Renewable Energy',
    'lesson.renewable.energy.desc': 'Discover clean energy sources like solar, wind, and hydroelectric power for a sustainable future.',
    
    // Lesson Content
    'lesson.waste.management.content': 'Understanding waste management is crucial for environmental protection. This lesson covers the 3 R\'s: Reduce, Reuse, and Recycle. You\'ll learn about different types of waste, proper sorting techniques, composting methods, and how individuals and communities can implement effective waste management strategies.',
    'lesson.water.treatment.content': 'Water treatment is essential for public health and environmental sustainability. Learn about the multi-step process including screening, sedimentation, filtration, and disinfection. Understand how wastewater treatment plants work and the importance of protecting our water resources.',
    'lesson.pollution.free.content': 'Creating pollution-free zones requires understanding different types of pollution and implementing comprehensive solutions. Learn about air quality monitoring, green transportation, industrial emission controls, and community-based environmental protection initiatives.',
    'lesson.afforestation.content': 'Afforestation is the process of establishing forests in areas where there were no previous tree cover. Learn about tree species selection, planting techniques, forest management, and the environmental benefits of creating new forest ecosystems.',
    'lesson.deforestation.content': 'Deforestation is the large-scale removal of forests, often for agriculture, logging, or urban development. Understand the causes, environmental impacts, and explore sustainable alternatives to protect our remaining forests.',
    'lesson.renewable.energy.content': 'Renewable energy comes from natural sources that are constantly replenished. Discover solar, wind, hydroelectric, and geothermal energy technologies and their role in creating a sustainable energy future.',
    
    // SDG Content
    'sdg.waste.management.title': '♻ Waste Management - Sustainable Development Goals',
    'sdg.water.treatment.title': '💧 Water Treatment - Sustainable Development Goals',
    'sdg.pollution.free.title': '🌱 Pollution-Free Zones - Sustainable Development Goals',
    'sdg.afforestation.title': '🌳 Afforestation - Sustainable Development Goals',
    'sdg.deforestation.title': '🌲 Deforestation - Sustainable Development Goals',
    'sdg.renewable.energy.title': '⚡ Renewable Energy - Sustainable Development Goals',
    
    // SDG Goals
    'sdg.12.title': 'Responsible Consumption and Production',
    'sdg.12.desc': 'Promote reduce, reuse, and recycle.',
    'sdg.11.title': 'Sustainable Cities and Communities',
    'sdg.11.desc': 'Cleaner cities through better waste systems.',
    'sdg.13.title': 'Climate Action',
    'sdg.13.desc': 'Less waste means fewer greenhouse gas emissions.',
    'sdg.6.title': 'Clean Water and Sanitation',
    'sdg.6.desc': 'Ensure access to water and sanitation for all through effective treatment systems.',
    'sdg.3.title': 'Good Health and Well-being',
    'sdg.3.desc': 'Protect public health by providing safe, clean water.',
    'sdg.14.title': 'Life Below Water',
    'sdg.14.desc': 'Prevent water pollution to protect marine ecosystems.',
    'sdg.15.title': 'Life on Land',
    'sdg.15.desc': 'Protect ecosystems from harmful air pollution.',
    'sdg.7.title': 'Affordable and Clean Energy',
    'sdg.7.desc': 'Ensure access to affordable, reliable, sustainable and modern energy for all.',
    'sdg.9.title': 'Industry, Innovation and Infrastructure',
    'sdg.9.desc': 'Build resilient infrastructure, promote inclusive and sustainable industrialization.',
    'sdg.aligns.with': 'This module aligns with the following Sustainable Development Goals:',
    
    // Video Descriptions
    'video.waste.management.desc': 'Watch this comprehensive guide to waste management practices and see real-world examples of successful recycling programs.',
    'video.water.treatment.desc': 'Take a virtual tour of a water treatment facility and see the amazing technology that keeps our water clean.',
    'video.pollution.free.desc': 'Discover successful pollution-free zone projects around the world and learn how communities are fighting pollution.',
    'video.afforestation.desc': 'Join forest restoration projects and witness the incredible transformation of barren land into thriving forests.',
    'video.deforestation.desc': 'Explore the impact of deforestation and discover how communities are working to protect their forests.',
    'video.renewable.energy.desc': 'See cutting-edge renewable energy installations and learn how clean energy is revolutionizing our world.',
    
    // Chatbot
    'chatbot.greeting': "Hi! I'm EcoLearn's helper. Ask me any environment question.",
    'chatbot.placeholder': 'Ask about waste, water, energy…',
    'chatbot.thinking': 'Thinking…',
    'chatbot.title': 'EcoLearn Assistant',
    'chatbot.ask.anything': 'Ask me anything',
    
    // Scoreboard
    'scoreboard.title': 'Your Achievements',
    'scoreboard.subtitle': 'Track your progress, earn badges, and celebrate your environmental learning journey! Every lesson completed makes you a better guardian of our planet.',
    'scoreboard.total.points': 'Total Points',
    'scoreboard.badges.earned': 'Badges Earned',
    'scoreboard.lessons.completed': 'Lessons Completed',
    'scoreboard.achievement.rate': 'Achievement Rate',
    'scoreboard.achievement.badges': 'Achievement Badges',
    'scoreboard.weekly.activity': 'Weekly Activity',
    'scoreboard.quick.stats': 'Quick Stats',
    'scoreboard.next.goal': 'Next Goal',
    'scoreboard.certificate.title': '🎓 Environmental Champion Certificate',
    'scoreboard.certificate.desc': 'Complete all 6 lessons to unlock your official Environmental Champion Certificate!',
    'scoreboard.progress.to.certificate': 'Progress to Certificate',
    'scoreboard.continue.learning': 'Continue Learning',
    'scoreboard.earned': 'Earned',
    'scoreboard.locked': 'Locked',
    'scoreboard.earned.on': 'Earned on',
    'scoreboard.progress': 'Progress',
    'scoreboard.study.streak': 'Study Streak',
    'scoreboard.avg.quiz.score': 'Average Quiz Score',
    'scoreboard.favorite.topic': 'Favorite Topic',
    'scoreboard.time.spent': 'Time Spent Learning',
    'scoreboard.lessons': 'lessons',
    'scoreboard.lesson': 'lesson',
    
    // Achievement badges
    'achievement.first.steps': 'First Steps',
    'achievement.first.steps.desc': 'Complete your first lesson',
    'achievement.quiz.master': 'Quiz Master',
    'achievement.quiz.master.desc': 'Score 100% on a quiz',
    'achievement.eco.warrior': 'Eco Warrior',
    'achievement.eco.warrior.desc': 'Complete 3 lessons',
    'achievement.speed.learner': 'Speed Learner',
    'achievement.speed.learner.desc': 'Complete a lesson in under 10 minutes',
    'achievement.perfect.score': 'Perfect Score',
    'achievement.perfect.score.desc': 'Get perfect scores on 3 quizzes',
    'achievement.dedicated.learner': 'Dedicated Learner',
    'achievement.dedicated.learner.desc': 'Study for 7 days in a row',
    
    // Lesson page
    'lesson.not.found': 'Lesson not found',
    'lesson.back.to.dashboard': 'Back to Dashboard',
    'lesson.interactive.lesson': 'Interactive Lesson',
    'lesson.video': '📹 Video',
    'lesson.game': '🎮 Game',
    'lesson.content': '📚 Content',
    'lesson.video.title': 'Lesson Video',
    'lesson.video.simulated': '📹 This is a simulated video player. In a real implementation, you would embed actual educational videos here.',
    'lesson.overview': 'Lesson Overview',
    'lesson.your.progress': 'Your Progress',
    'lesson.video.progress': 'Video Progress',
    'lesson.video.completed': 'Video completed!',
    'lesson.watch.complete': 'Watch the complete video to unlock the quiz',
    'lesson.ready.quiz': 'Ready for the Quiz?',
    'lesson.test.knowledge': 'Test your knowledge with our interactive quiz. Complete the video first to unlock it!',
    'lesson.complete.video.first': 'Complete Video First',
    'lesson.start.quiz': 'Start Quiz',
    'lesson.quick.facts': 'Quick Facts',
    
    // Lesson facts
    'fact.recycling.trees': 'Recycling 1 ton of paper saves 17 trees',
    'fact.composting.waste': 'Composting reduces waste by 30%',
    'fact.clean.water.diseases': 'Clean water prevents 80% of diseases',
    'fact.modern.plants.pollutants': 'Modern plants remove 99% of pollutants',
    'fact.every.action.difference': 'Every action makes a difference',
    'fact.together.protect.planet': 'Together we protect our planet',
    
    // Games
    'game.waste.title': 'Waste Sorting Challenge',
    'game.waste.description': 'Sort the waste items into the correct bins! Drag each item to its proper category.',
    'game.waste.recycling': 'Recycling',
    'game.waste.compost': 'Compost',
    'game.waste.trash': 'Trash',
    'game.waste.plastic.bottle': 'Plastic Bottle',
    'game.waste.banana.peel': 'Banana Peel',
    'game.waste.newspaper': 'Newspaper',
    'game.waste.chip.bag': 'Chip Bag',
    'game.waste.apple.core': 'Apple Core',
    'game.waste.glass.jar': 'Glass Jar',
    'game.waste.used.tissue': 'Used Tissue',
    'game.waste.coffee.grounds': 'Coffee Grounds',
    'game.waste.aluminum.can': 'Aluminum Can',
    'game.waste.candy.wrapper': 'Candy Wrapper',
    'game.waste.correct': 'Correct!',
    'game.waste.incorrect': 'Incorrect!',
    'game.waste.try.again': 'Try again!',
    'game.waste.completed': 'Great job! You sorted all the waste correctly!',
    'game.waste.restart': 'Restart Game',
    'game.waste.next.lesson': 'Next Lesson',
    
    // Water Treatment Game
    'game.water.title': 'Fix the Flow!',
    'game.water.description': 'Solve water conservation challenges with smart solutions',
    'game.water.instructions': 'Solve water problems by choosing the best conservation solution. Each correct answer earns 20 points!',
    'game.water.leaky.tap': 'Leaky Tap',
    'game.water.leaky.tap.problem': 'Water is dripping from this tap, wasting precious water!',
    'game.water.leaky.tap.solutions': 'Ignore it,Turn off valve,Add more taps',
    'game.water.leaky.tap.correct': 'Turn off valve',
    'game.water.leaky.tap.description': 'Fixing leaks saves thousands of gallons per year!',
    'game.water.dirty.water': 'Dirty Water',
    'game.water.dirty.water.problem': 'This water source is contaminated and needs treatment.',
    'game.water.dirty.water.solutions': 'Drink anyway,Install filter,Boil in microwave',
    'game.water.dirty.water.correct': 'Install filter',
    'game.water.dirty.water.description': 'Water filters remove 99% of harmful contaminants!',
    'game.water.rain.collection': 'Rain Collection',
    'game.water.rain.collection.problem': 'It\'s raining! How can we collect this clean water?',
    'game.water.rain.collection.solutions': 'Let it drain away,Install rain barrel,Use buckets only',
    'game.water.rain.collection.correct': 'Install rain barrel',
    'game.water.rain.collection.description': 'Rainwater harvesting reduces water bills by 40%!',
    'game.water.wastewater': 'Wastewater',
    'game.water.wastewater.problem': 'This dirty water needs to be cleaned before returning to nature.',
    'game.water.wastewater.solutions': 'Pour down drain,Treatment plant,Bury underground',
    'game.water.wastewater.correct': 'Treatment plant',
    'game.water.wastewater.description': 'Treatment plants clean 95% of pollutants from wastewater!',
    'game.water.garden.watering': 'Garden Watering',
    'game.water.garden.watering.problem': 'These plants need water, but we should conserve it.',
    'game.water.garden.watering.solutions': 'Use sprinkler all day,Drip irrigation,Water at noon',
    'game.water.garden.watering.correct': 'Drip irrigation',
    'game.water.garden.watering.description': 'Drip irrigation uses 50% less water than sprinklers!',
    'game.water.choose.solution': 'Choose the best solution:',
    'game.water.solved': 'Solved!',
    'game.water.correct': 'Correct!',
    'game.water.try.again': 'Try again!',
    'game.water.think.conservation': 'Think about water conservation!',
    'game.water.reset.game': 'Reset Game',
    'game.water.great.solution': 'Great solution! +20 points',
    'game.water.not.best.choice': 'Not the best choice. Try thinking about conservation!',
    
    // Deforestation Game
    'game.deforestation.title': 'Forest Guardian!',
    'game.deforestation.description': 'Arrange the conservation story in the right order to save the forest',
    'game.deforestation.instructions': 'Arrange the story panels in the correct order to show the forest conservation journey. Start with the problem, then show the solutions!',
    'game.deforestation.healthy.forest': 'Healthy Forest',
    'game.deforestation.healthy.forest.desc': 'A thriving forest ecosystem with diverse wildlife and clean air.',
    'game.deforestation.logging.begins': 'Logging Begins',
    'game.deforestation.logging.begins.desc': 'Trees are cut down for lumber and agriculture expansion.',
    'game.deforestation.forest.destruction': 'Forest Destruction',
    'game.deforestation.forest.destruction.desc': 'Large areas cleared, wildlife loses habitat, soil erodes.',
    'game.deforestation.community.action': 'Community Action',
    'game.deforestation.community.action.desc': 'Local communities organize to protect remaining forests.',
    'game.deforestation.sustainable.practices': 'Sustainable Practices',
    'game.deforestation.sustainable.practices.desc': 'Implement eco-friendly logging and replanting programs.',
    'game.deforestation.forest.recovery': 'Forest Recovery',
    'game.deforestation.forest.recovery.desc': 'New trees planted, wildlife returns, ecosystem restored.',
    'game.deforestation.problem': '⚠️ Problem',
    'game.deforestation.solution': '✅ Solution',
    'game.deforestation.position': 'Position',
    'game.deforestation.correct.position': 'Correct Position!',
    'game.deforestation.correct.positions': 'Correct Positions',
    'game.deforestation.moves.made': 'Moves Made',
    'game.deforestation.progress': 'Progress',
    'game.deforestation.correct.story.sequence': 'Correct Story Sequence:',
    'game.deforestation.problems': 'Problems (1-3)',
    'game.deforestation.action': 'Action (4)',
    'game.deforestation.solutions': 'Solutions (5-6)',
    'game.deforestation.healthy.to.logging': 'Healthy → Logging',
    'game.deforestation.logging.to.destruction': 'Logging → Destruction',
    'game.deforestation.community.organizes': 'Community organizes',
    'game.deforestation.sustainable.to.recovery': 'Sustainable → Recovery',
    'game.deforestation.story.panels': 'Story Panels (Arrange in Order):',
    'game.deforestation.story.complete': 'Story Complete!',
    'game.deforestation.story.complete.desc': 'You\'ve successfully shown how communities can protect and restore forests!',
    'game.deforestation.completed.in.moves': 'Completed in',
    'game.deforestation.shuffle.story': 'Shuffle Story',
    
    // Pollution Free Game
    'game.pollution.title': 'Clean City Challenge!',
    'game.pollution.description': 'Match pollution sources with eco-friendly solutions to improve air quality',
    'game.pollution.instructions': 'Match pollution sources with their eco-friendly solutions to improve air quality!',
    'game.pollution.air.quality.monitor': 'Air Quality Monitor',
    'game.pollution.excellent': 'Excellent',
    'game.pollution.good': 'Good',
    'game.pollution.moderate': 'Moderate',
    'game.pollution.poor': 'Poor',
    'game.pollution.clean': 'Clean',
    'game.pollution.pollution.sources': 'Pollution Sources:',
    'game.pollution.eco.solutions': 'Eco Solutions:',
    'game.pollution.car.emissions': 'Car Emissions',
    'game.pollution.factory.smoke': 'Factory Smoke',
    'game.pollution.plastic.waste': 'Plastic Waste',
    'game.pollution.coal.plant': 'Coal Plant',
    'game.pollution.garbage.dump': 'Garbage Dump',
    'game.pollution.truck.exhaust': 'Truck Exhaust',
    'game.pollution.electric.vehicle': 'Electric Vehicle',
    'game.pollution.green.factory': 'Green Factory',
    'game.pollution.recycling.center': 'Recycling Center',
    'game.pollution.solar.panels': 'Solar Panels',
    'game.pollution.composting': 'Composting',
    'game.pollution.electric.truck': 'Electric Truck',
    'game.pollution.fixed.with': 'Fixed with',
    'game.pollution.used': 'Used',
    'game.pollution.perfect.match': 'Perfect match! Pollution reduced! +15 points',
    'game.pollution.wrong.match': 'That solution doesn\'t match this pollution type. Try again!',
    'game.pollution.city.cleaned': 'City Cleaned!',
    'game.pollution.city.cleaned.desc': 'Air quality improved! The city can breathe easy now!',
    'game.pollution.reset.city': 'Reset City',
    
    // Afforestation Game
    'game.afforestation.title': 'Grow Green!',
    'game.afforestation.description': 'Plant trees in the right conditions and watch your forest thrive',
    'game.afforestation.instructions': 'Plant trees in the right soil types and water them to create a thriving forest!',
    'game.afforestation.trees.planted': 'Trees Planted',
    'game.afforestation.co2.absorbed': 'kg CO2/year absorbed',
    'game.afforestation.mature.trees': 'Mature Trees',
    'game.afforestation.seeds.to.plant': 'Seeds to Plant:',
    'game.afforestation.oak': 'Oak',
    'game.afforestation.pine': 'Pine',
    'game.afforestation.willow': 'Willow',
    'game.afforestation.maple': 'Maple',
    'game.afforestation.birch': 'Birch',
    'game.afforestation.cypress': 'Cypress',
    'game.afforestation.soil': 'soil',
    'game.afforestation.rich.soil': 'Rich Soil',
    'game.afforestation.rocky.soil': 'Rocky Soil',
    'game.afforestation.wetland': 'Wetland',
    'game.afforestation.drop.seed.here': 'Drop seed here',
    'game.afforestation.growth': 'Growth:',
    'game.afforestation.watered': 'Watered',
    'game.afforestation.water': 'Water',
    'game.afforestation.perfect.match': 'Perfect match! +15 points',
    'game.afforestation.tree.planted': 'Tree planted! +5 points (not optimal soil)',
    'game.afforestation.tree.watered': 'Tree watered! +10 points',
    'game.afforestation.all.seeds.planted': 'All seeds planted! Water your trees to help them grow!',
    'game.afforestation.your.forest': 'Your Forest:',
    'game.afforestation.forest.complete': 'Forest Complete!',
    'game.afforestation.forest.complete.desc': 'Your forest absorbs CO2 per year!',
    'game.afforestation.plant.new.forest': 'Plant New Forest',
    
    // Renewable Energy Game
    'game.renewable.title': 'Power Up!',
    'game.renewable.description': 'Build renewable energy sources to power an eco-friendly city',
    'game.renewable.instructions': 'Build renewable energy sources to power the entire city with clean energy!',
    'game.renewable.mw.generated': 'MW Generated',
    'game.renewable.mw.needed': 'MW Needed',
    'game.renewable.budget.left': 'Budget Left',
    'game.renewable.buildings.powered': 'Buildings Powered',
    'game.renewable.city.power.level': 'City Power Level',
    'game.renewable.renewable.sources': 'Renewable Sources:',
    'game.renewable.build.here': 'Build Here:',
    'game.renewable.city.buildings': 'City Buildings:',
    'game.renewable.solar.panel': 'Solar Panel',
    'game.renewable.wind.turbine': 'Wind Turbine',
    'game.renewable.hydro.dam': 'Hydro Dam',
    'game.renewable.geothermal': 'Geothermal',
    'game.renewable.output': 'Output:',
    'game.renewable.cost': 'Cost:',
    'game.renewable.efficiency': 'Efficiency:',
    'game.renewable.mountain': 'Mountain',
    'game.renewable.field': 'Field',
    'game.renewable.water': 'Water',
    'game.renewable.homes': 'Homes',
    'game.renewable.school': 'School',
    'game.renewable.hospital': 'Hospital',
    'game.renewable.office': 'Office',
    'game.renewable.factory': 'Factory',
    'game.renewable.mall': 'Mall',
    'game.renewable.powered': 'Powered',
    'game.renewable.needs': 'Needs',
    'game.renewable.not.enough.budget': 'Not enough budget!',
    'game.renewable.installed': 'installed! +20 points',
    'game.renewable.city.fully.powered': 'City Fully Powered!',
    'game.renewable.city.fully.powered.desc': '100% renewable energy achieved! The city is now carbon neutral!',
    'game.renewable.rebuild.city': 'Rebuild City',
    
    // Auth page
    'auth.subtitle': 'Learn about our environment and make a difference!',
    'auth.join.community': 'Join Our Community',
    'auth.start.journey': 'Start your environmental education journey today',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.full.name': 'Full Name',
    'auth.role': 'Role',
    'auth.student': 'Student',
    'auth.login.to.ecolearn': 'Login to EcoLearn',
    'auth.create.account': 'Create Account',
    'auth.welcome.back': 'Welcome back!',
    'auth.login.success': 'Login successful. Redirecting to dashboard...',
    'auth.account.created': 'Account created!',
    'auth.registration.success': 'Registration successful. Welcome to EcoLearn!',
    'auth.ready.explore': 'Ready to explore?',
    'auth.view.demo': 'View Demo Dashboard',
    'auth.email.placeholder': 'student@example.com',
    'auth.password.placeholder': 'Enter your password',
    'auth.name.placeholder': 'Alex Student',
    'auth.password.create.placeholder': 'Create a strong password',
    
    // Quiz
    'quiz.not.found': 'Quiz not found',
    'quiz.back.to.dashboard': 'Back to Dashboard',
    'quiz.complete': 'Quiz Complete!',
    'quiz.correct': 'Correct',
    'quiz.incorrect': 'Incorrect',
    'quiz.question': 'Question',
    'quiz.of': 'of',
    'quiz.correct.answer': 'Correct! 🎉',
    'quiz.great.job': 'Great job!',
    'quiz.oops': 'Oops! 😅',
    'quiz.keep.learning': 'Don\'t worry, keep learning!',
    'quiz.outstanding': 'Outstanding! You\'re an eco-expert! 🏆',
    'quiz.great.job.learning': 'Great job! You\'re learning well! 🌟',
    'quiz.keep.studying': 'Keep studying! You\'re on your way! 💪',
    'quiz.your.answers': 'Your Answers:',
    'quiz.retake.quiz': 'Retake Quiz',
    'quiz.view.achievements': 'View Achievements',
    'quiz.back.to.lesson': 'Back to Lesson',
    'quiz.submit.answer': 'Submit Answer',
    'quiz.next.question': 'Next Question',
    'quiz.view.results': 'View Results',
    'quiz.explanation': 'Explanation:',
    
    // Quiz Titles
    'quiz.waste.management.title': 'Waste Management Quiz',
    'quiz.water.treatment.title': 'Water Treatment Quiz',
    'quiz.pollution.free.title': 'Pollution-Free Zones Quiz',
    'quiz.afforestation.title': 'Afforestation Quiz',
    'quiz.deforestation.title': 'Deforestation Quiz',
    'quiz.renewable.energy.title': 'Renewable Energy Quiz',
    
    // Waste Management Quiz Questions
    'quiz.waste.q1.question': 'What are the 3 R\'s of waste management?',
    'quiz.waste.q1.option1': 'Reduce, Reuse, Recycle',
    'quiz.waste.q1.option2': 'Read, Write, Remember',
    'quiz.waste.q1.option3': 'Run, Rest, Repeat',
    'quiz.waste.q1.option4': 'Rock, Roll, Rhythm',
    'quiz.waste.q1.explanation': 'The 3 R\'s - Reduce, Reuse, and Recycle - are the fundamental principles of waste management that help minimize environmental impact.',
    
    'quiz.waste.q2.question': 'Which material takes the longest to decompose in landfills?',
    'quiz.waste.q2.option1': 'Paper',
    'quiz.waste.q2.option2': 'Glass',
    'quiz.waste.q2.option3': 'Plastic bottles',
    'quiz.waste.q2.option4': 'Food waste',
    'quiz.waste.q2.explanation': 'Glass can take over 1 million years to decompose, making it crucial to recycle glass products properly.',
    
    'quiz.waste.q3.question': 'What percentage of household waste can typically be composted?',
    'quiz.waste.q3.option1': '10%',
    'quiz.waste.q3.option2': '20%',
    'quiz.waste.q3.option3': '30%',
    'quiz.waste.q3.option4': '50%',
    'quiz.waste.q3.explanation': 'About 30% of household waste consists of organic materials that can be composted, significantly reducing landfill waste.',
    
    // Water Treatment Quiz Questions
    'quiz.water.q1.question': 'What is the first step in water treatment?',
    'quiz.water.q1.option1': 'Disinfection',
    'quiz.water.q1.option2': 'Screening',
    'quiz.water.q1.option3': 'Filtration',
    'quiz.water.q1.option4': 'Sedimentation',
    'quiz.water.q1.explanation': 'Screening is the first step, where large debris and particles are removed from the water before further treatment.',
    
    'quiz.water.q2.question': 'Which chemical is commonly used to disinfect water?',
    'quiz.water.q2.option1': 'Salt',
    'quiz.water.q2.option2': 'Chlorine',
    'quiz.water.q2.option3': 'Sugar',
    'quiz.water.q2.option4': 'Baking soda',
    'quiz.water.q2.explanation': 'Chlorine is widely used to disinfect water by killing harmful bacteria and viruses, making it safe for consumption.',
    
    'quiz.water.q3.question': 'How much of Earth\'s water is fresh and accessible?',
    'quiz.water.q3.option1': '10%',
    'quiz.water.q3.option2': '5%',
    'quiz.water.q3.option3': '3%',
    'quiz.water.q3.option4': 'Less than 1%',
    'quiz.water.q3.explanation': 'Less than 1% of Earth\'s water is fresh and accessible, making water conservation and treatment extremely important.',
    
    // Pollution-Free Zones Quiz Questions
    'quiz.pollution.q1.question': 'What is a major source of air pollution in cities?',
    'quiz.pollution.q1.option1': 'Trees',
    'quiz.pollution.q1.option2': 'Vehicle emissions',
    'quiz.pollution.q1.option3': 'Rainfall',
    'quiz.pollution.q1.option4': 'Wind',
    'quiz.pollution.q1.explanation': 'Vehicle emissions are one of the largest sources of air pollution in urban areas, contributing to smog and health problems.',
    
    'quiz.pollution.q2.question': 'Which transportation method produces the least pollution?',
    'quiz.pollution.q2.option1': 'Diesel bus',
    'quiz.pollution.q2.option2': 'Electric car',
    'quiz.pollution.q2.option3': 'Gasoline car',
    'quiz.pollution.q2.option4': 'Motorcycle',
    'quiz.pollution.q2.explanation': 'Electric vehicles produce zero direct emissions and are much cleaner than fossil fuel-powered vehicles.',
    
    'quiz.pollution.q3.question': 'What role do plants play in pollution-free zones?',
    'quiz.pollution.q3.option1': 'They increase pollution',
    'quiz.pollution.q3.option2': 'They absorb CO₂ and produce oxygen',
    'quiz.pollution.q3.option3': 'They have no effect',
    'quiz.pollution.q3.option4': 'They block sunlight',
    'quiz.pollution.q3.explanation': 'Plants naturally filter air by absorbing carbon dioxide and producing oxygen, making them essential for clean environments.',
    
    // Afforestation Quiz Questions
    'quiz.afforestation.q1.question': 'What is afforestation?',
    'quiz.afforestation.q1.option1': 'Cutting down forests',
    'quiz.afforestation.q1.option2': 'Planting trees in new areas',
    'quiz.afforestation.q1.option3': 'Moving forests',
    'quiz.afforestation.q1.option4': 'Painting trees',
    'quiz.afforestation.q1.explanation': 'Afforestation is the process of creating forests by planting trees in areas that were not previously forested.',
    
    'quiz.afforestation.q2.question': 'How do trees help fight climate change?',
    'quiz.afforestation.q2.option1': 'They reflect heat',
    'quiz.afforestation.q2.option2': 'They absorb carbon dioxide',
    'quiz.afforestation.q2.option3': 'They create wind',
    'quiz.afforestation.q2.option4': 'They block rain',
    'quiz.afforestation.q2.explanation': 'Trees absorb CO₂ from the atmosphere during photosynthesis, helping to reduce greenhouse gas concentrations.',
    
    'quiz.afforestation.q3.question': 'What\'s the best time to plant most trees?',
    'quiz.afforestation.q3.option1': 'Summer',
    'quiz.afforestation.q3.option2': 'Winter',
    'quiz.afforestation.q3.option3': 'Spring or Fall',
    'quiz.afforestation.q3.option4': 'Any time',
    'quiz.afforestation.q3.explanation': 'Spring and fall provide optimal conditions for tree planting, with moderate temperatures and adequate rainfall.',
    
    // Deforestation Quiz Questions
    'quiz.deforestation.q1.question': 'What is the main cause of deforestation globally?',
    'quiz.deforestation.q1.option1': 'Natural disasters',
    'quiz.deforestation.q1.option2': 'Agriculture expansion',
    'quiz.deforestation.q1.option3': 'Urban development',
    'quiz.deforestation.q1.option4': 'Disease',
    'quiz.deforestation.q1.explanation': 'Agriculture expansion, particularly for livestock and crop production, is responsible for about 80% of global deforestation.',
    
    'quiz.deforestation.q2.question': 'How does deforestation affect the water cycle?',
    'quiz.deforestation.q2.option1': 'No effect',
    'quiz.deforestation.q2.option2': 'Reduces rainfall',
    'quiz.deforestation.q2.option3': 'Increases rainfall',
    'quiz.deforestation.q2.option4': 'Changes water color',
    'quiz.deforestation.q2.explanation': 'Trees release water vapor through transpiration. Deforestation reduces this process, leading to decreased rainfall in the region.',
    
    'quiz.deforestation.q3.question': 'Which ecosystem service is lost when forests are cleared?',
    'quiz.deforestation.q3.option1': 'Carbon storage',
    'quiz.deforestation.q3.option2': 'Biodiversity habitat',
    'quiz.deforestation.q3.option3': 'Soil protection',
    'quiz.deforestation.q3.option4': 'All of the above',
    'quiz.deforestation.q3.explanation': 'Forests provide all these services - they store carbon, provide habitat for wildlife, and protect soil from erosion.',
    
    // Renewable Energy Quiz Questions
    'quiz.renewable.q1.question': 'Which is NOT a renewable energy source?',
    'quiz.renewable.q1.option1': 'Solar power',
    'quiz.renewable.q1.option2': 'Wind power',
    'quiz.renewable.q1.option3': 'Coal',
    'quiz.renewable.q1.option4': 'Hydroelectric',
    'quiz.renewable.q1.explanation': 'Coal is a fossil fuel that takes millions of years to form and produces harmful emissions when burned.',
    
    'quiz.renewable.q2.question': 'What makes solar panels work?',
    'quiz.renewable.q2.option1': 'Heat from the sun',
    'quiz.renewable.q2.option2': 'Light from the sun',
    'quiz.renewable.q2.option3': 'Wind',
    'quiz.renewable.q2.option4': 'Rain',
    'quiz.renewable.q2.explanation': 'Solar panels convert light (photons) from the sun into electricity through the photovoltaic effect.',
    
    'quiz.renewable.q3.question': 'Which renewable energy source works best at night?',
    'quiz.renewable.q3.option1': 'Solar',
    'quiz.renewable.q3.option2': 'Wind',
    'quiz.renewable.q3.option3': 'Hydroelectric',
    'quiz.renewable.q3.option4': 'Both B and C',
    'quiz.renewable.q3.explanation': 'Both wind and hydroelectric power can generate electricity 24/7, unlike solar power which only works during daylight.',
    
    // Real Time Tasks
    'realtime.tasks.title': 'Real Time Tasks',
    'realtime.tasks.subtitle': 'Join hands-on environmental activities and make a real impact in your community. Upload photos of your actions and inspire others!',
    'realtime.tasks.motivation.title': 'Make a Real Difference! 🌱',
    'realtime.tasks.motivation.description': 'Every photo you upload inspires others to take action. Together, we can create a greener, cleaner world for future generations.',
    
    // Task Status
    'task.status.active': 'Active',
    'task.status.coming.soon': 'Coming Soon',
    'task.status.inactive': 'Inactive',
    
    // Task Details
    'task.participants': 'Participants',
    'task.completed': 'Completed',
    'task.time.estimate': 'Time Estimate',
    'task.start.task': 'Start Task',
    'task.coming.soon': 'Coming Soon',
    'task.back.to.tasks': 'Back to Tasks',
    'task.view.achievements': 'View Achievements',
    'task.location': 'Location',
    'task.location.anywhere': 'Anywhere',
    'task.duration': 'Duration',
    'task.duration.15.30.min': '15-30 minutes',
    
    // Afforestation Task
    'task.afforestation.title': 'Plant a Tree Challenge',
    'task.afforestation.description': 'Plant a tree in your area and share photos to inspire others. Every tree makes a difference!',
    'task.afforestation.step1': 'Find a suitable location (your garden, park, or community area)',
    'task.afforestation.step2': 'Plant a tree or sapling following proper planting techniques',
    'task.afforestation.step3': 'Take photos of yourself planting and the planted tree',
    'task.afforestation.step4': 'Upload your photos and share your experience',
    
    // Community Cleanup Task
    'task.community.cleanup.title': 'Community Cleanup Drive',
    'task.community.cleanup.description': 'Organize or join a community cleanup event and document your efforts.',
    
    // Waste Audit Task
    'task.waste.audit.title': 'Waste Audit Challenge',
    'task.waste.audit.description': 'Conduct a waste audit in your home or community and share insights.',
    
    // Task Instructions
    'task.instructions.title': 'Task Instructions',
    
    // Upload Section
    'upload.title': 'Upload Your Photos',
    'upload.drag.drop': 'Drag & drop your photos here',
    'upload.or.click': 'or click to browse files',
    'upload.select.files': 'Select Photos',
    'upload.selected.files': 'Selected Files',
    'upload.progress': 'Uploading...',
    'upload.uploading': 'Uploading...',
    'upload.submit.task': 'Submit Task',
    
    // Upload Success/Error Messages
    'upload.success.title': 'Task Submitted! 🎉',
    'upload.success.description': 'Thank you for contributing to environmental protection! Your photos will inspire others.',
    'upload.error.title': 'Upload Error',
    'upload.error.invalid.file': 'Please select valid image files only.',
    'upload.error.too.many.files': 'You can upload maximum 5 photos at once.',
    'upload.error.no.files': 'Please select at least one photo to upload.',
    
    // Task Completion
    'task.completed.title': 'Task Completed! 🌟',
    'task.completed.description': 'Congratulations! You\'ve successfully completed the afforestation task. Your contribution helps make our planet greener!',
    
    // Common
    'common.minutes': 'min',
    'common.hours': 'hrs',
    'common.percent': '%',
    'common.points': 'pts',
    'common.days': 'days',
  },
  hi: {
    // Navigation
    'nav.dashboard': 'डैशबोर्ड',
    'nav.lessons': 'पाठ',
    'nav.realtime.tasks': 'रियल टाइम टास्क्स',
    'nav.scoreboard': 'स्कोरबोर्ड',
    'nav.logout': 'लॉग आउट',
    'nav.user': 'एलेक्स छात्र',
    'nav.logout.success': 'सफलतापूर्वक लॉग आउट हो गए',
    'nav.logout.message': 'फिर मिलते हैं!',
    
    // Dashboard
    'dashboard.welcome': 'आपकी पर्यावरणीय यात्रा में आपका स्वागत है! 🌍',
    'dashboard.subtitle': 'पर्यावरण संरक्षण और स्थिरता के बारे में इंटरैक्टिव पाठों का अन्वेषण करें। प्रत्येक पाठ में वीडियो, क्विज़ और हाथों से किए जाने वाले गतिविधियां शामिल हैं जो आपको एक इको-हीरो बनने में मदद करेंगी!',
    'dashboard.progress': 'प्रगति',
    'dashboard.overall.progress': 'कुल प्रगति',
    'dashboard.completed': 'पूर्ण',
    'dashboard.lessons.completed': 'पाठ पूर्ण',
    'dashboard.total.time': 'कुल समय',
    'dashboard.hours.learning': 'सीखने के घंटे',
    'dashboard.environmental.lessons': 'पर्यावरणीय पाठ',
    'dashboard.active.tasks': 'सक्रिय टास्क्स',
    'dashboard.tasks.available': 'उपलब्ध टास्क्स',
    'dashboard.community.size': 'समुदाय का आकार',
    'dashboard.active.participants': 'सक्रिय भागीदार',
    'dashboard.impact.made': 'प्रभाव डाला गया',
    'dashboard.tasks.completed': 'टास्क्स पूर्ण',
    'dashboard.keep.going': '🎯 चलते रहें, इको-योद्धा!',
    'dashboard.motivation': 'आप बहुत अच्छी प्रगति कर रहे हैं! प्रत्येक पाठ आपको पर्यावरणीय चैंपियन बनने के करीब लाता है।',
    'dashboard.view.achievements': 'अपनी उपलब्धियां देखें',
    
    // Lesson status
    'lesson.completed': '✓ पूर्ण',
    'lesson.complete': 'पूर्ण',
    'lesson.not.started': 'शुरू नहीं किया',
    'lesson.start': 'शुरू करें',
    'lesson.continue': 'जारी रखें',
    'lesson.review': 'समीक्षा करें',
    
    // Difficulty levels
    'difficulty.beginner': 'शुरुआती',
    'difficulty.intermediate': 'मध्यम',
    'difficulty.advanced': 'उन्नत',
    
    // Lessons
    'lesson.waste.management': 'अपशिष्ट प्रबंधन',
    'lesson.waste.management.desc': 'पर्यावरणीय प्रभाव को कम करने के लिए उचित अपशिष्ट निपटान, पुनर्चक्रण और खाद बनाने के बारे में जानें।',
    'lesson.water.treatment': 'जल उपचार',
    'lesson.water.treatment.desc': 'सुरक्षित उपभोग और पर्यावरण संरक्षण के लिए पानी को कैसे साफ और शुद्ध किया जाता है, इसकी खोज करें।',
    'lesson.pollution.free': 'प्रदूषण मुक्त क्षेत्र',
    'lesson.pollution.free.desc': 'शहरों में स्वच्छ, प्रदूषण मुक्त वातावरण बनाने और बनाए रखने की रणनीतियों का अन्वेषण करें।',
    'lesson.afforestation': 'वनरोपण',
    'lesson.afforestation.desc': 'हमारे ग्रह के लिए पेड़ लगाने और नए जंगल बनाने के महत्व को समझें।',
    'lesson.deforestation': 'वनों की कटाई',
    'lesson.deforestation.desc': 'वनों की कटाई के कारणों और प्रभावों के बारे में जानें और इसे कैसे रोकें।',
    'lesson.renewable.energy': 'नवीकरणीय ऊर्जा',
    'lesson.renewable.energy.desc': 'स्थिर भविष्य के लिए सौर, पवन और जलविद्युत शक्ति जैसे स्वच्छ ऊर्जा स्रोतों की खोज करें।',
    
    // Lesson Content
    'lesson.waste.management.content': 'अपशिष्ट प्रबंधन को समझना पर्यावरण संरक्षण के लिए महत्वपूर्ण है। यह पाठ 3 R के सिद्धांतों को कवर करता है: कम करना, पुन: उपयोग और पुनर्चक्रण। आप विभिन्न प्रकार के अपशिष्ट, उचित छंटाई तकनीकों, खाद बनाने की विधियों और व्यक्तियों और समुदायों द्वारा प्रभावी अपशिष्ट प्रबंधन रणनीतियों को कैसे लागू किया जा सकता है, इसके बारे में जानेंगे।',
    'lesson.water.treatment.content': 'जल उपचार सार्वजनिक स्वास्थ्य और पर्यावरणीय स्थिरता के लिए आवश्यक है। स्क्रीनिंग, अवसादन, निस्पंदन और कीटाणुशोधन सहित बहु-चरणीय प्रक्रिया के बारे में जानें। समझें कि अपशिष्ट जल उपचार संयंत्र कैसे काम करते हैं और हमारे जल संसाधनों की सुरक्षा का महत्व।',
    'lesson.pollution.free.content': 'प्रदूषण मुक्त क्षेत्र बनाने के लिए विभिन्न प्रकार के प्रदूषण को समझना और व्यापक समाधान लागू करना आवश्यक है। वायु गुणवत्ता निगरानी, हरित परिवहन, औद्योगिक उत्सर्जन नियंत्रण और समुदाय-आधारित पर्यावरण संरक्षण पहलों के बारे में जानें।',
    'lesson.afforestation.content': 'वनरोपण उन क्षेत्रों में जंगल स्थापित करने की प्रक्रिया है जहाँ पहले कोई वृक्ष आवरण नहीं था। वृक्ष प्रजाति चयन, रोपण तकनीकों, वन प्रबंधन और नए वन पारिस्थितिकी तंत्र बनाने के पर्यावरणीय लाभों के बारे में जानें।',
    'lesson.deforestation.content': 'वनों की कटाई जंगलों का बड़े पैमाने पर हटाना है, अक्सर कृषि, लॉगिंग या शहरी विकास के लिए। कारणों, पर्यावरणीय प्रभावों को समझें और हमारे शेष जंगलों की सुरक्षा के लिए स्थायी विकल्पों का अन्वेषण करें।',
    'lesson.renewable.energy.content': 'नवीकरणीय ऊर्जा प्राकृतिक स्रोतों से आती है जो लगातार पुनःपूर्ति होते रहते हैं। सौर, पवन, जलविद्युत और भूतापीय ऊर्जा प्रौद्योगिकियों और स्थायी ऊर्जा भविष्य बनाने में उनकी भूमिका की खोज करें।',
    
    // SDG Content
    'sdg.waste.management.title': '♻ अपशिष्ट प्रबंधन - सतत विकास लक्ष्य',
    'sdg.water.treatment.title': '💧 जल उपचार - सतत विकास लक्ष्य',
    'sdg.pollution.free.title': '🌱 प्रदूषण मुक्त क्षेत्र - सतत विकास लक्ष्य',
    'sdg.afforestation.title': '🌳 वनरोपण - सतत विकास लक्ष्य',
    'sdg.deforestation.title': '🌲 वनों की कटाई - सतत विकास लक्ष्य',
    'sdg.renewable.energy.title': '⚡ नवीकरणीय ऊर्जा - सतत विकास लक्ष्य',
    
    // SDG Goals
    'sdg.12.title': 'जिम्मेदार उपभोग और उत्पादन',
    'sdg.12.desc': 'कम करना, पुन: उपयोग और पुनर्चक्रण को बढ़ावा दें।',
    'sdg.11.title': 'स्थायी शहर और समुदाय',
    'sdg.11.desc': 'बेहतर अपशिष्ट प्रणालियों के माध्यम से स्वच्छ शहर।',
    'sdg.13.title': 'जलवायु कार्य',
    'sdg.13.desc': 'कम अपशिष्ट का मतलब कम ग्रीनहाउस गैस उत्सर्जन।',
    'sdg.6.title': 'स्वच्छ जल और स्वच्छता',
    'sdg.6.desc': 'प्रभावी उपचार प्रणालियों के माध्यम से सभी के लिए जल और स्वच्छता तक पहुंच सुनिश्चित करें।',
    'sdg.3.title': 'अच्छा स्वास्थ्य और कल्याण',
    'sdg.3.desc': 'सुरक्षित, स्वच्छ जल प्रदान करके सार्वजनिक स्वास्थ्य की रक्षा करें।',
    'sdg.14.title': 'जल के नीचे जीवन',
    'sdg.14.desc': 'समुद्री पारिस्थितिकी तंत्र की सुरक्षा के लिए जल प्रदूषण को रोकें।',
    'sdg.15.title': 'भूमि पर जीवन',
    'sdg.15.desc': 'हानिकारक वायु प्रदूषण से पारिस्थितिकी तंत्र की सुरक्षा करें।',
    'sdg.7.title': 'सस्ती और स्वच्छ ऊर्जा',
    'sdg.7.desc': 'सभी के लिए सस्ती, विश्वसनीय, स्थायी और आधुनिक ऊर्जा तक पहुंच सुनिश्चित करें।',
    'sdg.9.title': 'उद्योग, नवाचार और बुनियादी ढांचा',
    'sdg.9.desc': 'लचीले बुनियादी ढांचे का निर्माण करें, समावेशी और स्थायी औद्योगीकरण को बढ़ावा दें।',
    'sdg.aligns.with': 'यह मॉड्यूल निम्नलिखित सतत विकास लक्ष्यों के साथ संरेखित है:',
    
    // Video Descriptions
    'video.waste.management.desc': 'अपशिष्ट प्रबंधन प्रथाओं के इस व्यापक गाइड को देखें और सफल पुनर्चक्रण कार्यक्रमों के वास्तविक उदाहरण देखें।',
    'video.water.treatment.desc': 'जल उपचार सुविधा का आभासी दौरा करें और हमारे पानी को स्वच्छ रखने वाली अद्भुत तकनीक देखें।',
    'video.pollution.free.desc': 'दुनिया भर में सफल प्रदूषण मुक्त क्षेत्र परियोजनाओं की खोज करें और जानें कि समुदाय प्रदूषण से कैसे लड़ रहे हैं।',
    'video.afforestation.desc': 'वन बहाली परियोजनाओं में शामिल हों और बंजर भूमि के समृद्ध जंगलों में अविश्वसनीय परिवर्तन देखें।',
    'video.deforestation.desc': 'वनों की कटाई के प्रभाव का अन्वेषण करें और जानें कि समुदाय अपने जंगलों की सुरक्षा के लिए कैसे काम कर रहे हैं।',
    'video.renewable.energy.desc': 'अत्याधुनिक नवीकरणीय ऊर्जा स्थापनाओं को देखें और जानें कि स्वच्छ ऊर्जा हमारी दुनिया में क्रांति कैसे ला रही है।',
    
    // Chatbot
    'chatbot.greeting': 'नमस्ते! मैं EcoLearn का सहायक हूं। मुझसे कोई भी पर्यावरण प्रश्न पूछें।',
    'chatbot.placeholder': 'अपशिष्ट, पानी, ऊर्जा के बारे में पूछें…',
    'chatbot.thinking': 'सोच रहा है…',
    'chatbot.title': 'EcoLearn सहायक',
    'chatbot.ask.anything': 'मुझसे कुछ भी पूछें',
    
    // Scoreboard
    'scoreboard.title': 'आपकी उपलब्धियां',
    'scoreboard.subtitle': 'अपनी प्रगति को ट्रैक करें, बैज कमाएं, और अपनी पर्यावरणीय सीखने की यात्रा का जश्न मनाएं! हर पूर्ण पाठ आपको हमारे ग्रह का बेहतर रक्षक बनाता है।',
    'scoreboard.total.points': 'कुल अंक',
    'scoreboard.badges.earned': 'अर्जित बैज',
    'scoreboard.lessons.completed': 'पूर्ण पाठ',
    'scoreboard.achievement.rate': 'उपलब्धि दर',
    'scoreboard.achievement.badges': 'उपलब्धि बैज',
    'scoreboard.weekly.activity': 'साप्ताहिक गतिविधि',
    'scoreboard.quick.stats': 'त्वरित आंकड़े',
    'scoreboard.next.goal': 'अगला लक्ष्य',
    'scoreboard.certificate.title': '🎓 पर्यावरण चैंपियन प्रमाणपत्र',
    'scoreboard.certificate.desc': 'अपना आधिकारिक पर्यावरण चैंपियन प्रमाणपत्र अनलॉक करने के लिए सभी 6 पाठ पूर्ण करें!',
    'scoreboard.progress.to.certificate': 'प्रमाणपत्र की ओर प्रगति',
    'scoreboard.continue.learning': 'सीखना जारी रखें',
    'scoreboard.earned': 'अर्जित',
    'scoreboard.locked': 'लॉक',
    'scoreboard.earned.on': 'अर्जित किया गया',
    'scoreboard.progress': 'प्रगति',
    'scoreboard.study.streak': 'अध्ययन स्ट्रीक',
    'scoreboard.avg.quiz.score': 'औसत क्विज़ स्कोर',
    'scoreboard.favorite.topic': 'पसंदीदा विषय',
    'scoreboard.time.spent': 'सीखने में बिताया समय',
    'scoreboard.lessons': 'पाठ',
    'scoreboard.lesson': 'पाठ',
    
    // Achievement badges
    'achievement.first.steps': 'पहले कदम',
    'achievement.first.steps.desc': 'अपना पहला पाठ पूर्ण करें',
    'achievement.quiz.master': 'क्विज़ मास्टर',
    'achievement.quiz.master.desc': 'क्विज़ में 100% स्कोर करें',
    'achievement.eco.warrior': 'इको योद्धा',
    'achievement.eco.warrior.desc': '3 पाठ पूर्ण करें',
    'achievement.speed.learner': 'तेज़ सीखने वाला',
    'achievement.speed.learner.desc': '10 मिनट से कम में एक पाठ पूर्ण करें',
    'achievement.perfect.score': 'परफेक्ट स्कोर',
    'achievement.perfect.score.desc': '3 क्विज़ में परफेक्ट स्कोर प्राप्त करें',
    'achievement.dedicated.learner': 'समर्पित सीखने वाला',
    'achievement.dedicated.learner.desc': 'लगातार 7 दिन तक अध्ययन करें',
    
    // Lesson page
    'lesson.not.found': 'पाठ नहीं मिला',
    'lesson.back.to.dashboard': 'डैशबोर्ड पर वापस जाएं',
    'lesson.interactive.lesson': 'इंटरैक्टिव पाठ',
    'lesson.video': '📹 वीडियो',
    'lesson.game': '🎮 गेम',
    'lesson.content': '📚 सामग्री',
    'lesson.video.title': 'पाठ वीडियो',
    'lesson.video.simulated': '📹 यह एक सिम्युलेटेड वीडियो प्लेयर है। वास्तविक कार्यान्वयन में, आप यहां वास्तविक शैक्षिक वीडियो एम्बेड करेंगे।',
    'lesson.overview': 'पाठ अवलोकन',
    'lesson.your.progress': 'आपकी प्रगति',
    'lesson.video.progress': 'वीडियो प्रगति',
    'lesson.video.completed': 'वीडियो पूर्ण!',
    'lesson.watch.complete': 'क्विज़ अनलॉक करने के लिए पूरा वीडियो देखें',
    'lesson.ready.quiz': 'क्विज़ के लिए तैयार?',
    'lesson.test.knowledge': 'हमारे इंटरैक्टिव क्विज़ के साथ अपने ज्ञान का परीक्षण करें। इसे अनलॉक करने के लिए पहले वीडियो पूर्ण करें!',
    'lesson.complete.video.first': 'पहले वीडियो पूर्ण करें',
    'lesson.start.quiz': 'क्विज़ शुरू करें',
    'lesson.quick.facts': 'त्वरित तथ्य',
    
    // Lesson facts
    'fact.recycling.trees': '1 टन कागज रीसाइक्लिंग से 17 पेड़ बचते हैं',
    'fact.composting.waste': 'खाद बनाने से 30% अपशिष्ट कम होता है',
    'fact.clean.water.diseases': 'स्वच्छ पानी 80% बीमारियों को रोकता है',
    'fact.modern.plants.pollutants': 'आधुनिक संयंत्र 99% प्रदूषकों को हटाते हैं',
    'fact.every.action.difference': 'हर कार्य फर्क लाता है',
    'fact.together.protect.planet': 'मिलकर हम अपने ग्रह की रक्षा करते हैं',
    
    // Games
    'game.waste.title': 'अपशिष्ट छंटाई चुनौती',
    'game.waste.description': 'अपशिष्ट वस्तुओं को सही डिब्बों में छांटें! प्रत्येक वस्तु को उसकी उचित श्रेणी में खींचें।',
    'game.waste.recycling': 'रीसाइक्लिंग',
    'game.waste.compost': 'खाद',
    'game.waste.trash': 'कचरा',
    'game.waste.plastic.bottle': 'प्लास्टिक बोतल',
    'game.waste.banana.peel': 'केले का छिलका',
    'game.waste.newspaper': 'अखबार',
    'game.waste.chip.bag': 'चिप्स का पैकेट',
    'game.waste.apple.core': 'सेब का गूदा',
    'game.waste.glass.jar': 'कांच का जार',
    'game.waste.used.tissue': 'इस्तेमाल किया गया टिशू',
    'game.waste.coffee.grounds': 'कॉफी की पिसी हुई बीन्स',
    'game.waste.aluminum.can': 'एल्यूमीनियम कैन',
    'game.waste.candy.wrapper': 'कैंडी का रैपर',
    'game.waste.correct': 'सही!',
    'game.waste.incorrect': 'गलत!',
    'game.waste.try.again': 'फिर से कोशिश करें!',
    'game.waste.completed': 'बहुत बढ़िया! आपने सभी अपशिष्ट को सही तरीके से छांटा!',
    'game.waste.restart': 'गेम दोबारा शुरू करें',
    'game.waste.next.lesson': 'अगला पाठ',
    
    // Water Treatment Game
    'game.water.title': 'प्रवाह ठीक करें!',
    'game.water.description': 'स्मार्ट समाधानों के साथ जल संरक्षण चुनौतियों को हल करें',
    'game.water.instructions': 'सबसे अच्छे संरक्षण समाधान का चयन करके जल समस्याओं को हल करें। प्रत्येक सही उत्तर 20 अंक कमाता है!',
    'game.water.leaky.tap': 'टपकता नल',
    'game.water.leaky.tap.problem': 'इस नल से पानी टपक रहा है, कीमती पानी बर्बाद हो रहा है!',
    'game.water.leaky.tap.solutions': 'इसे नजरअंदाज करें,वाल्व बंद करें,और नल लगाएं',
    'game.water.leaky.tap.correct': 'वाल्व बंद करें',
    'game.water.leaky.tap.description': 'लीक ठीक करने से हजारों गैलन पानी बचता है!',
    'game.water.dirty.water': 'गंदा पानी',
    'game.water.dirty.water.problem': 'यह जल स्रोत दूषित है और उपचार की आवश्यकता है।',
    'game.water.dirty.water.solutions': 'फिर भी पी लें,फिल्टर लगाएं,माइक्रोवेव में उबालें',
    'game.water.dirty.water.correct': 'फिल्टर लगाएं',
    'game.water.dirty.water.description': 'जल फिल्टर 99% हानिकारक दूषित पदार्थों को हटाते हैं!',
    'game.water.rain.collection': 'वर्षा संग्रह',
    'game.water.rain.collection.problem': 'बारिश हो रही है! हम इस स्वच्छ पानी को कैसे इकट्ठा कर सकते हैं?',
    'game.water.rain.collection.solutions': 'बहने दें,वर्षा बैरल लगाएं,केवल बाल्टी का उपयोग करें',
    'game.water.rain.collection.correct': 'वर्षा बैरल लगाएं',
    'game.water.rain.collection.description': 'वर्षा जल संचयन से जल बिल 40% कम होता है!',
    'game.water.wastewater': 'अपशिष्ट जल',
    'game.water.wastewater.problem': 'प्रकृति में वापस जाने से पहले इस गंदे पानी को साफ करना होगा।',
    'game.water.wastewater.solutions': 'नाली में डालें,उपचार संयंत्र,जमीन में दबा दें',
    'game.water.wastewater.correct': 'उपचार संयंत्र',
    'game.water.wastewater.description': 'उपचार संयंत्र अपशिष्ट जल से 95% प्रदूषकों को साफ करते हैं!',
    'game.water.garden.watering': 'बगीचे की सिंचाई',
    'game.water.garden.watering.problem': 'इन पौधों को पानी की आवश्यकता है, लेकिन हमें इसका संरक्षण करना चाहिए।',
    'game.water.garden.watering.solutions': 'पूरे दिन स्प्रिंकलर का उपयोग करें,ड्रिप सिंचाई,दोपहर में पानी दें',
    'game.water.garden.watering.correct': 'ड्रिप सिंचाई',
    'game.water.garden.watering.description': 'ड्रिप सिंचाई स्प्रिंकलर की तुलना में 50% कम पानी का उपयोग करती है!',
    'game.water.choose.solution': 'सबसे अच्छा समाधान चुनें:',
    'game.water.solved': 'हल हो गया!',
    'game.water.correct': 'सही!',
    'game.water.try.again': 'फिर से कोशिश करें!',
    'game.water.think.conservation': 'जल संरक्षण के बारे में सोचें!',
    'game.water.reset.game': 'गेम रीसेट करें',
    'game.water.great.solution': 'बहुत अच्छा समाधान! +20 अंक',
    'game.water.not.best.choice': 'सबसे अच्छा विकल्प नहीं। संरक्षण के बारे में सोचने की कोशिश करें!',
    
    // Deforestation Game
    'game.deforestation.title': 'वन रक्षक!',
    'game.deforestation.description': 'वन संरक्षण कहानी को सही क्रम में व्यवस्थित करके जंगल को बचाएं',
    'game.deforestation.instructions': 'वन संरक्षण यात्रा को दिखाने के लिए कहानी पैनलों को सही क्रम में व्यवस्थित करें। समस्या से शुरू करें, फिर समाधान दिखाएं!',
    'game.deforestation.healthy.forest': 'स्वस्थ जंगल',
    'game.deforestation.healthy.forest.desc': 'विविध वन्यजीव और स्वच्छ हवा के साथ एक समृद्ध वन पारिस्थितिकी तंत्र।',
    'game.deforestation.logging.begins': 'लकड़ी काटना शुरू',
    'game.deforestation.logging.begins.desc': 'लकड़ी और कृषि विस्तार के लिए पेड़ काटे जाते हैं।',
    'game.deforestation.forest.destruction': 'वन विनाश',
    'game.deforestation.forest.destruction.desc': 'बड़े क्षेत्र साफ किए गए, वन्यजीवों का आवास खो गया, मिट्टी का कटाव।',
    'game.deforestation.community.action': 'समुदाय कार्य',
    'game.deforestation.community.action.desc': 'स्थानीय समुदाय शेष जंगलों की रक्षा के लिए संगठित होते हैं।',
    'game.deforestation.sustainable.practices': 'स्थायी प्रथाएं',
    'game.deforestation.sustainable.practices.desc': 'पर्यावरण-अनुकूल लकड़ी काटने और पुनः रोपण कार्यक्रम लागू करें।',
    'game.deforestation.forest.recovery': 'वन पुनर्स्थापना',
    'game.deforestation.forest.recovery.desc': 'नए पेड़ लगाए गए, वन्यजीव वापस आए, पारिस्थितिकी तंत्र बहाल।',
    'game.deforestation.problem': '⚠️ समस्या',
    'game.deforestation.solution': '✅ समाधान',
    'game.deforestation.position': 'स्थिति',
    'game.deforestation.correct.position': 'सही स्थिति!',
    'game.deforestation.correct.positions': 'सही स्थितियां',
    'game.deforestation.moves.made': 'चालें चली',
    'game.deforestation.progress': 'प्रगति',
    'game.deforestation.correct.story.sequence': 'सही कहानी क्रम:',
    'game.deforestation.problems': 'समस्याएं (1-3)',
    'game.deforestation.action': 'कार्य (4)',
    'game.deforestation.solutions': 'समाधान (5-6)',
    'game.deforestation.healthy.to.logging': 'स्वस्थ → लकड़ी काटना',
    'game.deforestation.logging.to.destruction': 'लकड़ी काटना → विनाश',
    'game.deforestation.community.organizes': 'समुदाय संगठित होता है',
    'game.deforestation.sustainable.to.recovery': 'स्थायी → पुनर्स्थापना',
    'game.deforestation.story.panels': 'कहानी पैनल (क्रम में व्यवस्थित करें):',
    'game.deforestation.story.complete': 'कहानी पूर्ण!',
    'game.deforestation.story.complete.desc': 'आपने सफलतापूर्वक दिखाया कि समुदाय जंगलों की रक्षा और पुनर्स्थापना कैसे कर सकते हैं!',
    'game.deforestation.completed.in.moves': 'चालों में पूर्ण',
    'game.deforestation.shuffle.story': 'कहानी फेरबदल करें',
    
    // Pollution Free Game
    'game.pollution.title': 'स्वच्छ शहर चुनौती!',
    'game.pollution.description': 'हवा की गुणवत्ता में सुधार के लिए प्रदूषण स्रोतों को पर्यावरण-अनुकूल समाधानों के साथ मिलाएं',
    'game.pollution.instructions': 'हवा की गुणवत्ता में सुधार के लिए प्रदूषण स्रोतों को उनके पर्यावरण-अनुकूल समाधानों के साथ मिलाएं!',
    'game.pollution.air.quality.monitor': 'हवा की गुणवत्ता मॉनिटर',
    'game.pollution.excellent': 'उत्कृष्ट',
    'game.pollution.good': 'अच्छा',
    'game.pollution.moderate': 'मध्यम',
    'game.pollution.poor': 'खराब',
    'game.pollution.clean': 'स्वच्छ',
    'game.pollution.pollution.sources': 'प्रदूषण स्रोत:',
    'game.pollution.eco.solutions': 'पर्यावरण समाधान:',
    'game.pollution.car.emissions': 'कार उत्सर्जन',
    'game.pollution.factory.smoke': 'कारखाने का धुआं',
    'game.pollution.plastic.waste': 'प्लास्टिक कचरा',
    'game.pollution.coal.plant': 'कोयला संयंत्र',
    'game.pollution.garbage.dump': 'कचरा डंप',
    'game.pollution.truck.exhaust': 'ट्रक का धुआं',
    'game.pollution.electric.vehicle': 'इलेक्ट्रिक वाहन',
    'game.pollution.green.factory': 'हरित कारखाना',
    'game.pollution.recycling.center': 'रीसाइक्लिंग केंद्र',
    'game.pollution.solar.panels': 'सौर पैनल',
    'game.pollution.composting': 'खाद बनाना',
    'game.pollution.electric.truck': 'इलेक्ट्रिक ट्रक',
    'game.pollution.fixed.with': 'से ठीक किया गया',
    'game.pollution.used': 'उपयोग किया गया',
    'game.pollution.perfect.match': 'परफेक्ट मैच! प्रदूषण कम हुआ! +15 अंक',
    'game.pollution.wrong.match': 'वह समाधान इस प्रदूषण प्रकार से मेल नहीं खाता। फिर से कोशिश करें!',
    'game.pollution.city.cleaned': 'शहर साफ हो गया!',
    'game.pollution.city.cleaned.desc': 'हवा की गुणवत्ता में सुधार हुआ! अब शहर आसानी से सांस ले सकता है!',
    'game.pollution.reset.city': 'शहर रीसेट करें',
    
    // Afforestation Game
    'game.afforestation.title': 'हरा उगाएं!',
    'game.afforestation.description': 'सही परिस्थितियों में पेड़ लगाएं और अपने जंगल को फलते-फूलते देखें',
    'game.afforestation.instructions': 'सही मिट्टी के प्रकारों में पेड़ लगाएं और उन्हें पानी दें ताकि एक समृद्ध जंगल बन सके!',
    'game.afforestation.trees.planted': 'पेड़ लगाए गए',
    'game.afforestation.co2.absorbed': 'किलो CO2/वर्ष अवशोषित',
    'game.afforestation.mature.trees': 'परिपक्व पेड़',
    'game.afforestation.seeds.to.plant': 'लगाने के लिए बीज:',
    'game.afforestation.oak': 'ओक',
    'game.afforestation.pine': 'पाइन',
    'game.afforestation.willow': 'विलो',
    'game.afforestation.maple': 'मेपल',
    'game.afforestation.birch': 'बर्च',
    'game.afforestation.cypress': 'साइप्रस',
    'game.afforestation.soil': 'मिट्टी',
    'game.afforestation.rich.soil': 'उपजाऊ मिट्टी',
    'game.afforestation.rocky.soil': 'चट्टानी मिट्टी',
    'game.afforestation.wetland': 'दलदली भूमि',
    'game.afforestation.drop.seed.here': 'यहां बीज डालें',
    'game.afforestation.growth': 'वृद्धि',
    'game.afforestation.watered': 'पानी दिया गया',
    'game.afforestation.water': 'पानी दें',
    'game.afforestation.perfect.match': 'परफेक्ट मैच! +15 अंक',
    'game.afforestation.tree.planted': 'पेड़ लगाया गया! +5 अंक (इष्टतम मिट्टी नहीं)',
    'game.afforestation.tree.watered': 'पेड़ को पानी दिया गया! +10 अंक',
    'game.afforestation.all.seeds.planted': 'सभी बीज लगाए गए! अपने पेड़ों को बढ़ने में मदद करने के लिए उन्हें पानी दें!',
    'game.afforestation.your.forest': 'आपका जंगल:',
    'game.afforestation.forest.complete': 'जंगल पूर्ण!',
    'game.afforestation.forest.complete.desc': 'आपका जंगल प्रति वर्ष CO2 अवशोषित करता है!',
    'game.afforestation.plant.new.forest': 'नया जंगल लगाएं',
    
    // Renewable Energy Game
    'game.renewable.title': 'पावर अप!',
    'game.renewable.description': 'पूरे शहर को स्वच्छ ऊर्जा से बिजली देने के लिए नवीकरणीय ऊर्जा स्रोत बनाएं',
    'game.renewable.instructions': 'पूरे शहर को स्वच्छ ऊर्जा से बिजली देने के लिए नवीकरणीय ऊर्जा स्रोत बनाएं!',
    'game.renewable.mw.generated': 'MW उत्पन्न',
    'game.renewable.mw.needed': 'MW आवश्यक',
    'game.renewable.budget.left': 'बजट बचा',
    'game.renewable.buildings.powered': 'भवन बिजली से चल रहे',
    'game.renewable.city.power.level': 'शहर बिजली स्तर',
    'game.renewable.renewable.sources': 'नवीकरणीय स्रोत:',
    'game.renewable.build.here': 'यहां बनाएं:',
    'game.renewable.city.buildings': 'शहर के भवन:',
    'game.renewable.solar.panel': 'सौर पैनल',
    'game.renewable.wind.turbine': 'पवन टरबाइन',
    'game.renewable.hydro.dam': 'जलविद्युत बांध',
    'game.renewable.geothermal': 'भूतापीय',
    'game.renewable.output': 'उत्पादन:',
    'game.renewable.cost': 'लागत:',
    'game.renewable.efficiency': 'दक्षता:',
    'game.renewable.mountain': 'पहाड़',
    'game.renewable.field': 'खेत',
    'game.renewable.water': 'पानी',
    'game.renewable.homes': 'घर',
    'game.renewable.school': 'स्कूल',
    'game.renewable.hospital': 'अस्पताल',
    'game.renewable.office': 'कार्यालय',
    'game.renewable.factory': 'कारखाना',
    'game.renewable.mall': 'मॉल',
    'game.renewable.powered': 'बिजली से चल रहा',
    'game.renewable.needs': 'आवश्यकता',
    'game.renewable.not.enough.budget': 'पर्याप्त बजट नहीं!',
    'game.renewable.installed': 'स्थापित! +20 अंक',
    'game.renewable.city.fully.powered': 'शहर पूरी तरह से बिजली से चल रहा!',
    'game.renewable.city.fully.powered.desc': '100% नवीकरणीय ऊर्जा हासिल! शहर अब कार्बन न्यूट्रल है!',
    'game.renewable.rebuild.city': 'शहर का पुनर्निर्माण करें',
    
    // Auth page
    'auth.subtitle': 'हमारे पर्यावरण के बारे में जानें और फर्क लाएं!',
    'auth.join.community': 'हमारे समुदाय में शामिल हों',
    'auth.start.journey': 'आज ही अपनी पर्यावरणीय शिक्षा यात्रा शुरू करें',
    'auth.login': 'लॉग इन',
    'auth.register': 'रजिस्टर',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.full.name': 'पूरा नाम',
    'auth.role': 'भूमिका',
    'auth.student': 'छात्र',
    'auth.login.to.ecolearn': 'EcoLearn में लॉग इन करें',
    'auth.create.account': 'खाता बनाएं',
    'auth.welcome.back': 'वापस स्वागत है!',
    'auth.login.success': 'लॉग इन सफल। डैशबोर्ड पर रीडायरेक्ट हो रहे हैं...',
    'auth.account.created': 'खाता बन गया!',
    'auth.registration.success': 'रजिस्ट्रेशन सफल। EcoLearn में आपका स्वागत है!',
    'auth.ready.explore': 'अन्वेषण के लिए तैयार?',
    'auth.view.demo': 'डेमो डैशबोर्ड देखें',
    'auth.email.placeholder': 'student@example.com',
    'auth.password.placeholder': 'अपना पासवर्ड दर्ज करें',
    'auth.name.placeholder': 'एलेक्स छात्र',
    'auth.password.create.placeholder': 'एक मजबूत पासवर्ड बनाएं',
    
    // Quiz
    'quiz.not.found': 'क्विज़ नहीं मिला',
    'quiz.back.to.dashboard': 'डैशबोर्ड पर वापस जाएं',
    'quiz.complete': 'क्विज़ पूर्ण!',
    'quiz.correct': 'सही',
    'quiz.incorrect': 'गलत',
    'quiz.question': 'प्रश्न',
    'quiz.of': 'का',
    'quiz.correct.answer': 'सही! 🎉',
    'quiz.great.job': 'बहुत बढ़िया!',
    'quiz.oops': 'ओह! 😅',
    'quiz.keep.learning': 'चिंता न करें, सीखना जारी रखें!',
    'quiz.outstanding': 'उत्कृष्ट! आप एक इको-विशेषज्ञ हैं! 🏆',
    'quiz.great.job.learning': 'बहुत बढ़िया! आप अच्छी तरह सीख रहे हैं! 🌟',
    'quiz.keep.studying': 'अध्ययन जारी रखें! आप सही रास्ते पर हैं! 💪',
    'quiz.your.answers': 'आपके उत्तर:',
    'quiz.retake.quiz': 'क्विज़ दोबारा करें',
    'quiz.view.achievements': 'उपलब्धियां देखें',
    'quiz.back.to.lesson': 'पाठ पर वापस जाएं',
    'quiz.submit.answer': 'उत्तर जमा करें',
    'quiz.next.question': 'अगला प्रश्न',
    'quiz.view.results': 'परिणाम देखें',
    'quiz.explanation': 'व्याख्या:',
    
    // Quiz Titles
    'quiz.waste.management.title': 'अपशिष्ट प्रबंधन क्विज़',
    'quiz.water.treatment.title': 'जल उपचार क्विज़',
    'quiz.pollution.free.title': 'प्रदूषण मुक्त क्षेत्र क्विज़',
    'quiz.afforestation.title': 'वनरोपण क्विज़',
    'quiz.deforestation.title': 'वनों की कटाई क्विज़',
    'quiz.renewable.energy.title': 'नवीकरणीय ऊर्जा क्विज़',
    
    // Waste Management Quiz Questions
    'quiz.waste.q1.question': 'अपशिष्ट प्रबंधन के 3 R क्या हैं?',
    'quiz.waste.q1.option1': 'कम करें, पुनः उपयोग, पुनर्चक्रण',
    'quiz.waste.q1.option2': 'पढ़ें, लिखें, याद रखें',
    'quiz.waste.q1.option3': 'दौड़ें, आराम करें, दोहराएं',
    'quiz.waste.q1.option4': 'रॉक, रोल, रिदम',
    'quiz.waste.q1.explanation': '3 R - कम करें, पुनः उपयोग और पुनर्चक्रण - अपशिष्ट प्रबंधन के मौलिक सिद्धांत हैं जो पर्यावरणीय प्रभाव को कम करने में मदद करते हैं।',
    
    'quiz.waste.q2.question': 'कौन सी सामग्री लैंडफिल में सबसे लंबे समय तक विघटित होती है?',
    'quiz.waste.q2.option1': 'कागज',
    'quiz.waste.q2.option2': 'कांच',
    'quiz.waste.q2.option3': 'प्लास्टिक की बोतलें',
    'quiz.waste.q2.option4': 'खाद्य अपशिष्ट',
    'quiz.waste.q2.explanation': 'कांच को विघटित होने में 1 मिलियन से अधिक वर्ष लग सकते हैं, इसलिए कांच के उत्पादों का उचित पुनर्चक्रण करना महत्वपूर्ण है।',
    
    'quiz.waste.q3.question': 'घरेलू अपशिष्ट का कितना प्रतिशत आमतौर पर खाद बनाया जा सकता है?',
    'quiz.waste.q3.option1': '10%',
    'quiz.waste.q3.option2': '20%',
    'quiz.waste.q3.option3': '30%',
    'quiz.waste.q3.option4': '50%',
    'quiz.waste.q3.explanation': 'घरेलू अपशिष्ट का लगभग 30% जैविक सामग्री से बना होता है जिसे खाद बनाया जा सकता है, जो लैंडफिल अपशिष्ट को काफी कम करता है।',
    
    // Water Treatment Quiz Questions
    'quiz.water.q1.question': 'जल उपचार में पहला कदम क्या है?',
    'quiz.water.q1.option1': 'कीटाणुशोधन',
    'quiz.water.q1.option2': 'छानना',
    'quiz.water.q1.option3': 'फिल्टर करना',
    'quiz.water.q1.option4': 'अवसादन',
    'quiz.water.q1.explanation': 'छानना पहला कदम है, जहां आगे के उपचार से पहले पानी से बड़े मलबे और कणों को हटाया जाता है।',
    
    'quiz.water.q2.question': 'पानी को कीटाणुरहित करने के लिए कौन सा रसायन आमतौर पर उपयोग किया जाता है?',
    'quiz.water.q2.option1': 'नमक',
    'quiz.water.q2.option2': 'क्लोरीन',
    'quiz.water.q2.option3': 'चीनी',
    'quiz.water.q2.option4': 'बेकिंग सोडा',
    'quiz.water.q2.explanation': 'क्लोरीन का व्यापक रूप से पानी को कीटाणुरहित करने के लिए उपयोग किया जाता है, हानिकारक बैक्टीरिया और वायरस को मारकर इसे उपभोग के लिए सुरक्षित बनाता है।',
    
    'quiz.water.q3.question': 'पृथ्वी का कितना पानी ताजा और सुलभ है?',
    'quiz.water.q3.option1': '10%',
    'quiz.water.q3.option2': '5%',
    'quiz.water.q3.option3': '3%',
    'quiz.water.q3.option4': '1% से कम',
    'quiz.water.q3.explanation': 'पृथ्वी का 1% से कम पानी ताजा और सुलभ है, जो जल संरक्षण और उपचार को अत्यंत महत्वपूर्ण बनाता है।',
    
    // Pollution-Free Zones Quiz Questions
    'quiz.pollution.q1.question': 'शहरों में वायु प्रदूषण का एक प्रमुख स्रोत क्या है?',
    'quiz.pollution.q1.option1': 'पेड़',
    'quiz.pollution.q1.option2': 'वाहन उत्सर्जन',
    'quiz.pollution.q1.option3': 'वर्षा',
    'quiz.pollution.q1.option4': 'हवा',
    'quiz.pollution.q1.explanation': 'वाहन उत्सर्जन शहरी क्षेत्रों में वायु प्रदूषण के सबसे बड़े स्रोतों में से एक है, जो धुंध और स्वास्थ्य समस्याओं में योगदान देता है।',
    
    'quiz.pollution.q2.question': 'कौन सा परिवहन तरीका सबसे कम प्रदूषण उत्पन्न करता है?',
    'quiz.pollution.q2.option1': 'डीजल बस',
    'quiz.pollution.q2.option2': 'इलेक्ट्रिक कार',
    'quiz.pollution.q2.option3': 'गैसोलीन कार',
    'quiz.pollution.q2.option4': 'मोटरसाइकिल',
    'quiz.pollution.q2.explanation': 'इलेक्ट्रिक वाहन शून्य प्रत्यक्ष उत्सर्जन उत्पन्न करते हैं और जीवाश्म ईंधन से चलने वाले वाहनों की तुलना में बहुत स्वच्छ हैं।',
    
    'quiz.pollution.q3.question': 'प्रदूषण मुक्त क्षेत्रों में पौधों की क्या भूमिका है?',
    'quiz.pollution.q3.option1': 'वे प्रदूषण बढ़ाते हैं',
    'quiz.pollution.q3.option2': 'वे CO₂ अवशोषित करते हैं और ऑक्सीजन उत्पन्न करते हैं',
    'quiz.pollution.q3.option3': 'उनका कोई प्रभाव नहीं है',
    'quiz.pollution.q3.option4': 'वे सूर्य के प्रकाश को रोकते हैं',
    'quiz.pollution.q3.explanation': 'पौधे कार्बन डाइऑक्साइड अवशोषित करके और ऑक्सीजन उत्पन्न करके प्राकृतिक रूप से हवा को फिल्टर करते हैं, जो उन्हें स्वच्छ वातावरण के लिए आवश्यक बनाता है।',
    
    // Afforestation Quiz Questions
    'quiz.afforestation.q1.question': 'वनरोपण क्या है?',
    'quiz.afforestation.q1.option1': 'जंगलों को काटना',
    'quiz.afforestation.q1.option2': 'नए क्षेत्रों में पेड़ लगाना',
    'quiz.afforestation.q1.option3': 'जंगलों को स्थानांतरित करना',
    'quiz.afforestation.q1.option4': 'पेड़ों को रंगना',
    'quiz.afforestation.q1.explanation': 'वनरोपण उन क्षेत्रों में पेड़ लगाकर जंगल बनाने की प्रक्रिया है जो पहले वनाच्छादित नहीं थे।',
    
    'quiz.afforestation.q2.question': 'पेड़ जलवायु परिवर्तन से लड़ने में कैसे मदद करते हैं?',
    'quiz.afforestation.q2.option1': 'वे गर्मी को प्रतिबिंबित करते हैं',
    'quiz.afforestation.q2.option2': 'वे कार्बन डाइऑक्साइड अवशोषित करते हैं',
    'quiz.afforestation.q2.option3': 'वे हवा बनाते हैं',
    'quiz.afforestation.q2.option4': 'वे बारिश को रोकते हैं',
    'quiz.afforestation.q2.explanation': 'पेड़ प्रकाश संश्लेषण के दौरान वायुमंडल से CO₂ अवशोषित करते हैं, जो ग्रीनहाउस गैस सांद्रता को कम करने में मदद करता है।',
    
    'quiz.afforestation.q3.question': 'अधिकांश पेड़ लगाने का सबसे अच्छा समय क्या है?',
    'quiz.afforestation.q3.option1': 'गर्मी',
    'quiz.afforestation.q3.option2': 'सर्दी',
    'quiz.afforestation.q3.option3': 'वसंत या पतझड़',
    'quiz.afforestation.q3.option4': 'कोई भी समय',
    'quiz.afforestation.q3.explanation': 'वसंत और पतझड़ पेड़ लगाने के लिए इष्टतम स्थिति प्रदान करते हैं, मध्यम तापमान और पर्याप्त वर्षा के साथ।',
    
    // Deforestation Quiz Questions
    'quiz.deforestation.q1.question': 'वैश्विक स्तर पर वनों की कटाई का मुख्य कारण क्या है?',
    'quiz.deforestation.q1.option1': 'प्राकृतिक आपदाएं',
    'quiz.deforestation.q1.option2': 'कृषि विस्तार',
    'quiz.deforestation.q1.option3': 'शहरी विकास',
    'quiz.deforestation.q1.option4': 'रोग',
    'quiz.deforestation.q1.explanation': 'कृषि विस्तार, विशेष रूप से पशुधन और फसल उत्पादन के लिए, वैश्विक वनों की कटाई के लगभग 80% के लिए जिम्मेदार है।',
    
    'quiz.deforestation.q2.question': 'वनों की कटाई जल चक्र को कैसे प्रभावित करती है?',
    'quiz.deforestation.q2.option1': 'कोई प्रभाव नहीं',
    'quiz.deforestation.q2.option2': 'वर्षा कम करती है',
    'quiz.deforestation.q2.option3': 'वर्षा बढ़ाती है',
    'quiz.deforestation.q2.option4': 'पानी का रंग बदलती है',
    'quiz.deforestation.q2.explanation': 'पेड़ वाष्पोत्सर्जन के माध्यम से जल वाष्प छोड़ते हैं। वनों की कटाई इस प्रक्रिया को कम करती है, जिससे क्षेत्र में वर्षा में कमी आती है।',
    
    'quiz.deforestation.q3.question': 'जंगलों को साफ करने पर कौन सी पारिस्थितिकी तंत्र सेवा खो जाती है?',
    'quiz.deforestation.q3.option1': 'कार्बन भंडारण',
    'quiz.deforestation.q3.option2': 'जैव विविधता आवास',
    'quiz.deforestation.q3.option3': 'मिट्टी संरक्षण',
    'quiz.deforestation.q3.option4': 'उपरोक्त सभी',
    'quiz.deforestation.q3.explanation': 'जंगल ये सभी सेवाएं प्रदान करते हैं - वे कार्बन संग्रहीत करते हैं, वन्यजीवों के लिए आवास प्रदान करते हैं, और मिट्टी को कटाव से बचाते हैं।',
    
    // Renewable Energy Quiz Questions
    'quiz.renewable.q1.question': 'कौन सा नवीकरणीय ऊर्जा स्रोत नहीं है?',
    'quiz.renewable.q1.option1': 'सौर ऊर्जा',
    'quiz.renewable.q1.option2': 'पवन ऊर्जा',
    'quiz.renewable.q1.option3': 'कोयला',
    'quiz.renewable.q1.option4': 'जलविद्युत',
    'quiz.renewable.q1.explanation': 'कोयला एक जीवाश्म ईंधन है जो बनने में लाखों वर्ष लगते हैं और जलाने पर हानिकारक उत्सर्जन उत्पन्न करता है।',
    
    'quiz.renewable.q2.question': 'सौर पैनल कैसे काम करते हैं?',
    'quiz.renewable.q2.option1': 'सूर्य से गर्मी',
    'quiz.renewable.q2.option2': 'सूर्य से प्रकाश',
    'quiz.renewable.q2.option3': 'हवा',
    'quiz.renewable.q2.option4': 'बारिश',
    'quiz.renewable.q2.explanation': 'सौर पैनल फोटोवोल्टिक प्रभाव के माध्यम से सूर्य से प्रकाश (फोटॉन) को बिजली में परिवर्तित करते हैं।',
    
    'quiz.renewable.q3.question': 'कौन सा नवीकरणीय ऊर्जा स्रोत रात में सबसे अच्छा काम करता है?',
    'quiz.renewable.q3.option1': 'सौर',
    'quiz.renewable.q3.option2': 'पवन',
    'quiz.renewable.q3.option3': 'जलविद्युत',
    'quiz.renewable.q3.option4': 'B और C दोनों',
    'quiz.renewable.q3.explanation': 'पवन और जलविद्युत दोनों 24/7 बिजली उत्पन्न कर सकते हैं, सौर ऊर्जा के विपरीत जो केवल दिन के समय काम करती है।',
    
    // Real Time Tasks
    'realtime.tasks.title': 'रियल टाइम टास्क्स',
    'realtime.tasks.subtitle': 'हाथों से किए जाने वाली पर्यावरणीय गतिविधियों में शामिल हों और अपने समुदाय में वास्तविक प्रभाव डालें। अपने कार्यों की तस्वीरें अपलोड करें और दूसरों को प्रेरित करें!',
    'realtime.tasks.motivation.title': 'वास्तविक फर्क लाएं! 🌱',
    'realtime.tasks.motivation.description': 'आपके द्वारा अपलोड की गई हर तस्वीर दूसरों को कार्य करने के लिए प्रेरित करती है। मिलकर हम भविष्य की पीढ़ियों के लिए एक हरा-भरा, स्वच्छ दुनिया बना सकते हैं।',
    
    // Task Status
    'task.status.active': 'सक्रिय',
    'task.status.coming.soon': 'जल्द आ रहा है',
    'task.status.inactive': 'निष्क्रिय',
    
    // Task Details
    'task.participants': 'भागीदार',
    'task.completed': 'पूर्ण',
    'task.time.estimate': 'समय अनुमान',
    'task.start.task': 'टास्क शुरू करें',
    'task.coming.soon': 'जल्द आ रहा है',
    'task.back.to.tasks': 'टास्क्स पर वापस जाएं',
    'task.view.achievements': 'उपलब्धियां देखें',
    'task.location': 'स्थान',
    'task.location.anywhere': 'कहीं भी',
    'task.duration': 'अवधि',
    'task.duration.15.30.min': '15-30 मिनट',
    
    // Afforestation Task
    'task.afforestation.title': 'पेड़ लगाएं चुनौती',
    'task.afforestation.description': 'अपने क्षेत्र में एक पेड़ लगाएं और दूसरों को प्रेरित करने के लिए तस्वीरें साझा करें। हर पेड़ फर्क लाता है!',
    'task.afforestation.step1': 'एक उपयुक्त स्थान खोजें (आपका बगीचा, पार्क, या समुदाय क्षेत्र)',
    'task.afforestation.step2': 'उचित रोपण तकनीकों का पालन करते हुए एक पेड़ या पौधा लगाएं',
    'task.afforestation.step3': 'अपने रोपण और लगाए गए पेड़ की तस्वीरें लें',
    'task.afforestation.step4': 'अपनी तस्वीरें अपलोड करें और अपना अनुभव साझा करें',
    
    // Community Cleanup Task
    'task.community.cleanup.title': 'समुदाय सफाई अभियान',
    'task.community.cleanup.description': 'एक समुदाय सफाई कार्यक्रम का आयोजन करें या उसमें शामिल हों और अपने प्रयासों को दस्तावेज करें।',
    
    // Waste Audit Task
    'task.waste.audit.title': 'अपशिष्ट ऑडिट चुनौती',
    'task.waste.audit.description': 'अपने घर या समुदाय में अपशिष्ट ऑडिट करें और अंतर्दृष्टि साझा करें।',
    
    // Task Instructions
    'task.instructions.title': 'टास्क निर्देश',
    
    // Upload Section
    'upload.title': 'अपनी तस्वीरें अपलोड करें',
    'upload.drag.drop': 'अपनी तस्वीरें यहां खींचें और छोड़ें',
    'upload.or.click': 'या फाइलें ब्राउज़ करने के लिए क्लिक करें',
    'upload.select.files': 'तस्वीरें चुनें',
    'upload.selected.files': 'चयनित फाइलें',
    'upload.progress': 'अपलोड हो रहा है...',
    'upload.uploading': 'अपलोड हो रहा है...',
    'upload.submit.task': 'टास्क जमा करें',
    
    // Upload Success/Error Messages
    'upload.success.title': 'टास्क जमा हो गया! 🎉',
    'upload.success.description': 'पर्यावरण संरक्षण में योगदान देने के लिए धन्यवाद! आपकी तस्वीरें दूसरों को प्रेरित करेंगी।',
    'upload.error.title': 'अपलोड त्रुटि',
    'upload.error.invalid.file': 'कृपया केवल वैध छवि फाइलें चुनें।',
    'upload.error.too.many.files': 'आप एक बार में अधिकतम 5 तस्वीरें अपलोड कर सकते हैं।',
    'upload.error.no.files': 'अपलोड करने के लिए कृपया कम से कम एक तस्वीर चुनें।',
    
    // Task Completion
    'task.completed.title': 'टास्क पूर्ण! 🌟',
    'task.completed.description': 'बधाई हो! आपने सफलतापूर्वक वनरोपण टास्क पूर्ण किया है। आपका योगदान हमारे ग्रह को हरा-भरा बनाने में मदद करता है!',
    
    // Common
    'common.minutes': 'मिनट',
    'common.hours': 'घंटे',
    'common.percent': '%',
    'common.points': 'अंक',
    'common.days': 'दिन',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'hi' : 'en');
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
